---
- name: VERIFY ACL SETTINGS
  hosts: ios
  connection: network_cli
  gather_facts: no
  
  tasks:

  - name: CHECK REACHABILITY
    ios_facts:

  - name: CHECKING ACL
    ios_command:
      commands:
        - show ip access-list VTY
    register: result

  - debug:
      var: result.stdout

