---
- name: CHECK IOS VERSION
  hosts: ios
  connection: network_cli
  gather_facts: no
  
  tasks:
  
  - name: GATHER ROUTER FACTS
    ios_facts:
      
  - name: CHECKING MODEL
    ios_command:
      commands:  
        - sh int status | i VM
    register: output
  
  - debug:
      var: output.stdout
        

