---
- name: VERIFY NTP SETTINGS
  hosts: ios
  connection: network_cli
  gather_facts: no
  
  tasks:

  - name: CHECK REACHABILITY
    ios_facts:

  - name: CHECKING NTP CONFIGURATIONS
    ios_command:
      commands:
        - sh run | i ntp authentication-key
    register: result

  - debug:
      var: result.stdout

